# Mega Quiz - Banco de Perguntas (500 por categoria)
# Direitos Reservados - ezetecf@gmail.com

import random, itertools

# ====================== HELPERS ======================

def make_q(question, options, answer, diff=0):
    return {"q": question, "o": options, "a": answer, "d": diff}

def pick_distractors(correct, pool, n=3):
    others = [x for x in pool if x != correct]
    sample = random.sample(others, min(n, len(others)))
    opts = [correct] + sample
    random.shuffle(opts)
    return opts, opts.index(correct)

# ====================== LANGUAGE WORD LISTS ======================

def make_lang_pairs():
    bases = [
        ("water","agua"),("fire","fogo"),("earth","terra"),("air","ar"),
        ("sun","sol"),("moon","lua"),("star","estrela"),("sky","ceu"),
        ("tree","arvore"),("flower","flor"),("grass","grama"),("mountain","montanha"),
        ("river","rio"),("ocean","oceano"),("sea","mar"),("rain","chuva"),
        ("snow","neve"),("wind","vento"),("cloud","nuvem"),("thunder","trovao"),
        ("house","casa"),("door","porta"),("window","janela"),("wall","parede"),
        ("table","mesa"),("chair","cadeira"),("bed","cama"),("kitchen","cozinha"),
        ("bathroom","banheiro"),("garden","jardim"),("school","escola"),("hospital","hospital"),
        ("church","igreja"),("market","mercado"),("street","rua"),("bridge","ponte"),
        ("car","carro"),("bus","onibus"),("train","trem"),("plane","aviao"),
        ("dog","cachorro"),("cat","gato"),("bird","passaro"),("fish","peixe"),
        ("horse","cavalo"),("cow","vaca"),("lion","leao"),("elephant","elefante"),
        ("book","livro"),("pen","caneta"),("paper","papel"),("pencil","lapis"),
        ("teacher","professor"),("student","aluno"),("friend","amigo"),("family","familia"),
        ("father","pai"),("mother","mae"),("brother","irmao"),("sister","irma"),
        ("happy","feliz"),("sad","triste"),("angry","bravo"),("tired","cansado"),
        ("hungry","com fome"),("thirsty","com sede"),("beautiful","bonito"),("ugly","feio"),
        ("big","grande"),("small","pequeno"),("fast","rapido"),("slow","devagar"),
        ("hot","quente"),("cold","frio"),("new","novo"),("old","velho"),
        ("good","bom"),("bad","ruim"),("rich","rico"),("poor","pobre"),
        ("love","amor"),("hate","odio"),("peace","paz"),("war","guerra"),
        ("life","vida"),("death","morte"),("hope","esperanca"),("faith","fe"),
        ("time","tempo"),("day","dia"),("night","noite"),("year","ano"),
        ("today","hoje"),("yesterday","ontem"),("tomorrow","amanha"),("always","sempre"),
        ("never","nunca"),("now","agora"),("here","aqui"),("there","ali"),
        ("hello","ola"),("goodbye","tchau"),("please","por favor"),("sorry","desculpe"),
        ("food","comida"),("drink","bebida"),("bread","pao"),("milk","leite"),
        ("meat","carne"),("fruit","fruta"),("rice","arroz"),("soup","sopa"),
        ("salt","sal"),("sugar","acucar"),("coffee","cafe"),("tea","cha"),
        ("juice","suco"),("wine","vinho"),("butter","manteiga"),("cheese","queijo"),
        ("egg","ovo"),("apple","maca"),("banana","banana"),("grape","uva"),
        ("orange","laranja"),("lemon","limao"),("head","cabeca"),("eye","olho"),
        ("ear","orelha"),("mouth","boca"),("nose","nariz"),("hand","mao"),
        ("foot","pe"),("arm","braco"),("leg","perna"),("heart","coracao"),
        ("head","cabeca"),("hair","cabelo"),("tooth","dente"),("tongue","lingua"),
        ("red","vermelho"),("blue","azul"),("green","verde"),("yellow","amarelo"),
        ("white","branco"),("black","preto"),("gray","cinza"),("brown","marrom"),
        ("pink","rosa"),("purple","roxo"),("orange","laranja"),("gold","dourado"),
        ("silver","prata"),("iron","ferro"),("wood","madeira"),("stone","pedra"),
        ("glass","vidro"),("paper","papel"),("leather","couro"),("silk","seda"),
        ("cotton","algodao"),("wool","la"),("gold","ouro"),("diamond","diamante"),
        ("summer","verao"),("winter","inverno"),("spring","primavera"),("autumn","outono"),
        ("january","janeiro"),("february","fevereiro"),("march","marco"),("april","abril"),
        ("may","maio"),("june","junho"),("july","julho"),("august","agosto"),
        ("september","setembro"),("october","outubro"),("november","novembro"),("december","dezembro"),
        ("monday","segunda"),("tuesday","terca"),("wednesday","quarta"),("thursday","quinta"),
        ("friday","sexta"),("saturday","sabado"),("sunday","domingo"),
        ("one","um"),("two","dois"),("three","tres"),("four","quatro"),
        ("five","cinco"),("six","seis"),("seven","sete"),("eight","oito"),
        ("nine","nove"),        ("ten","dez"),("hundred","cem"),("thousand","mil"),
        ("first","primeiro"),("second","segundo"),("last","ultimo"),("next","proximo"),
        ("before","antes"),("after","depois"),("open","abrir"),("close","fechar"),
        ("enter","entrar"),("exit","sair"),("come","vir"),("go","ir"),
        ("run","correr"),("walk","andar"),("swim","nadar"),("sleep","dormir"),
        ("eat","comer"),("drink","beber"),("read","ler"),("write","escrever"),
        ("speak","falar"),("listen","ouvir"),("sing","cantar"),("dance","dancar"),
        ("play","jogar"),("work","trabalhar"),("study","estudar"),("teach","ensinar"),
        ("learn","aprender"),("buy","comprar"),("sell","vender"),("cook","cozinhar"),
        ("wash","lavar"),("clean","limpar"),("repair","consertar"),("build","construir"),
        ("think","pensar"),("know","saber"),("believe","acreditar"),("understand","entender"),
        ("remember","lembrar"),("forget","esquecer"),("want","querer"),("need","precisar"),
        ("can","poder"),("must","dever"),("maybe","talvez"),("also","tambem"),
        ("very","muito"),("more","mais"),("less","menos"),("enough","suficiente"),
        ("still","ainda"),("already","ja"),("yet","ainda"),("just","apenas"),
        ("only","somente"),("almost","quase"),("even","ate"),("again","novamente"),
        ("together","juntos"),("alone","sozinho"),("etcetera","etc"),("example","exemplo"),
    ]
    return bases

def gen_lang_questions(word_pairs, lang_name):
    qs = []
    pool_pt = [p[1] for p in word_pairs]
    pool_word = [p[0] for p in word_pairs]

    total = len(word_pairs)
    for idx, (word, meaning) in enumerate(word_pairs):
        diff = 0 if idx < total * 0.4 else (1 if idx < total * 0.75 else 2)
        opts, a = pick_distractors(meaning, pool_pt)
        qs.append(make_q(f"Qual a traducao de '{word.title()}' para portugues?", opts, a, diff))

    for idx, (word, meaning) in enumerate(word_pairs):
        diff = 0 if idx < total * 0.4 else (1 if idx < total * 0.75 else 2)
        opts, a = pick_distractors(word, pool_word)
        qs.append(make_q(f"Como se diz '{meaning.title()}' em {lang_name}?", opts, a, diff))

    random.shuffle(qs)
    return qs[:500]

# ====================== WORD LISTS ======================

EN_BASE = make_lang_pairs()

SP_BASE = [(e, p) for e, p in make_lang_pairs()]

FR_BASE = [
    ("eau","agua"),("feu","fogo"),("terre","terra"),("air","ar"),
    ("soleil","sol"),("lune","lua"),("etoile","estrela"),("ciel","ceu"),
    ("arbre","arvore"),("fleur","flor"),("montagne","montanha"),("riviere","rio"),
    ("mer","mar"),("pluie","chuva"),("neige","neve"),("vent","vento"),
    ("nuage","nuvem"),("maison","casa"),("porte","porta"),("fenetre","janela"),
    ("table","mesa"),("chaise","cadeira"),("lit","cama"),("cuisine","cozinha"),
    ("ecole","escola"),("eglise","igreja"),("marche","mercado"),("rue","rua"),
    ("voiture","carro"),("bus","onibus"),("train","trem"),("avion","aviao"),
    ("chien","cachorro"),("chat","gato"),("oiseau","passaro"),("poisson","peixe"),
    ("cheval","cavalo"),("vache","vaca"),("lion","leao"),("elephant","elefante"),
    ("livre","livro"),("stylo","caneta"),("papier","papel"),("crayon","lapis"),
    ("professeur","professor"),("ami","amigo"),("famille","familia"),
    ("pere","pai"),("mere","mae"),("frere","irmao"),("soeur","irma"),
    ("heureux","feliz"),("triste","triste"),("facile","facil"),("difficile","dificil"),
    ("beau","bonito"),("laid","feio"),("grand","grande"),("petit","pequeno"),
    ("rapide","rapido"),("lent","devagar"),("chaud","quente"),("froid","frio"),
    ("nouveau","novo"),("vieux","velho"),("bon","bom"),("mauvais","ruim"),
    ("amour","amor"),("paix","paz"),("guerre","guerra"),("vie","vida"),
    ("mort","morte"),("espoir","esperanca"),("foi","fe"),("temps","tempo"),
    ("jour","dia"),("nuit","noite"),("an","ano"),("hier","ontem"),
    ("demain","amanha"),("toujours","sempre"),("jamais","nunca"),("maintenant","agora"),
    ("ici","aqui"),("la","ali"),("bonjour","ola"),("au revoir","tchau"),
    ("merci","obrigado"),("pardon","desculpe"),("rouge","vermelho"),("bleu","azul"),
    ("vert","verde"),("jaune","amarelo"),("blanc","branco"),("noir","preto"),
    ("pain","pao"),("lait","leite"),("viande","carne"),("fruit","fruta"),
    ("riz","arroz"),("soupe","sopa"),("sel","sal"),("sucre","acucar"),
    ("cafe","cafe"),("the","cha"),("jus","suco"),("vin","vinho"),
    ("beurre","manteiga"),("fromage","queijo"),("oeuf","ovo"),
    ("pomme","maca"),("banane","banana"),("raisin","uva"),("orange","laranja"),
    ("citron","limao"),("tete","cabeca"),("oeil","olho"),("oreille","orelha"),
    ("bouche","boca"),("nez","nariz"),("main","mao"),("pied","pe"),
    ("bras","braco"),("jambe","perna"),("coeur","coracao"),("cheveux","cabelo"),
    ("dent","dente"),("langue","lingua"),
    ("premier","primeiro"),("second","segundo"),("dernier","ultimo"),("prochain","proximo"),
    ("avant","antes"),("apres","depois"),("ouvrir","abrir"),("fermer","fechar"),
    ("entrer","entrar"),("sortir","sair"),("venir","vir"),("aller","ir"),
    ("courir","correr"),("marcher","andar"),("nager","nadar"),("dormir","dormir"),
    ("manger","comer"),("boire","beber"),("lire","ler"),("ecrire","escrever"),
    ("parler","falar"),("ecouter","ouvir"),("chanter","cantar"),("danser","dancar"),
    ("jouer","jogar"),("travailler","trabalhar"),("etudier","estudar"),("enseigner","ensinar"),
    ("apprendre","aprender"),("acheter","comprar"),("vendre","vender"),("cuisiner","cozinhar"),
    ("laver","lavar"),("nettoyer","limpar"),("reparer","consertar"),("construire","construir"),
    ("penser","pensar"),("savoir","saber"),("croire","acreditar"),("comprendre","entender"),
    ("se souvenir","lembrar"),("oublier","esquecer"),("vouloir","querer"),("devoir","dever"),
    ("peut-etre","talvez"),("aussi","tambem"),("tres","muito"),("plus","mais"),
    ("moins","menos"),("assez","suficiente"),("encore","ainda"),("deja","ja"),
    ("seulement","somente"),("presque","quase"),("meme","ate"),("encore","novamente"),
    ("ensemble","juntos"),("seul","sozinho"),("ete","verao"),("hiver","inverno"),
    ("printemps","primavera"),("automne","outono"),("lundi","segunda"),("mardi","terca"),
    ("mercredi","quarta"),("jeudi","quinta"),("vendredi","sexta"),("samedi","sabado"),
    ("dimanche","domingo"),("janvier","janeiro"),("fevrier","fevereiro"),("mars","marco"),
    ("avril","abril"),("mai","maio"),("juin","junho"),("juillet","julho"),
    ("aout","agosto"),("septembre","setembro"),("octobre","outubro"),("novembre","novembro"),
    ("decembre","dezembro"),("un","um"),("deux","dois"),("trois","tres"),
    ("quatre","quatro"),("cinq","cinco"),("six","seis"),("sept","sete"),
    ("huit","oito"),("neuf","nove"),("dix","dez"),("cent","cem"),
    ("mille","mil"),("tete","cabeca"),("main","mao"),("pied","pe"),
    ("bras","braco"),("doigt","dedo"),("genou","joelho"),("coude","cotovelo"),
    ("epaule","ombro"),("dos","costas"),("ventre","barriga"),("hanche","quadril"),
    ("table","mesa"),("chaise","cadeira"),("lampe","lampada"),("tapie","tapete"),
    ("rideau","cortina"),("coussin","almofada"),("miroir","espelho"),("horloge","relogio"),
    ("bureau","escrivaninha"),("etagere","estante"),("armoire","armario"),("tiroir","gaveta"),
    ("fourchette","garfo"),("cuillere","colher"),("couteau","faca"),("assiette","prato"),
    ("verre","copo"),("tasse","xicara"),("bol","tigela"),("serviette","guardanapo"),
    ("nappe","toalha"),("tablier","avental"),("torchon","pano"),("eponge","esponja"),
    ("savon","sabao"),("shampooing","shampoo"),("brosse","escova"),("peigne","pente"),
    ("serviette","toalha"),("gant","luva"),("echarpe","cachecol"),("chapeau","chapeu"),
    ("manteau","casaco"),("veste","jaqueta"),("chemise","camisa"),("pantalon","calca"),
    ("chaussette","meia"),("chaussure","sapato"),("botte","bota"),("sandale","sandalia"),
    ("ceinture","cinto"),("montre","relogio"),("collier","colar"),("bague","anel"),
    ("boucle d'oreille","brinco"),("bracelet","pulseira"),("lunettes","oculos"),
    ("parapluie","guarda-chuva"),("sac","bolsa"),("porte-monnaie","carteira"),
    ("cle","chave"),("serrure","fechadura"),("cadenas","cadeado"),
    ("papier","papel"),("enveloppe","envelope"),("timbre","selo"),
    ("carte","mapa"),("dictionnaire","dicionario"),("cahier","caderno"),
    ("gomme","borracha"),("regle","regua"),("compas","compasso"),
    ("calculatrice","calculadora"),("ordinateur","computador"),
    ("clavier","teclado"),("souris","mouse"),("ecran","tela"),
    ("imprimante","impressora"),("scanner","scanner"),("telephone","telefone"),
]

KO_BASE = [
    ("mul","agua"),("bul","fogo"),("ttang","terra"),("haneul","ceu"),
    ("hae","sol"),("dal","lua"),("byeol","estrela"),("gureum","nuvem"),
    ("namu","arvore"),("kkot","flor"),("san","montanha"),("gang","rio"),
    ("bada","mar"),("bi","chuva"),("nun","neve"),("baram","vento"),
    ("jip","casa"),("mun","porta"),("chang","janela"),("sikdang","restaurante"),
    ("hakgyo","escola"),("byeongwon","hospital"),("gyohoe","igreja"),("gil","rua"),
    ("cha","carro"),("beoseu","onibus"),("gicha","trem"),("bihaenggi","aviao"),
    ("gae","cachorro"),("goyangi","gato"),("saega","passaro"),("mulgogi","peixe"),
    ("mal","cavalo"),("so","vaca"),("saja","leao"),("kkokkiri","elefante"),
    ("chaek","livro"),("pen","caneta"),("jong-i","papel"),("yeonpil","lapis"),
    ("seonsaengnim","professor"),("haksaeng","aluno"),("chingu","amigo"),("gajok","familia"),
    ("abeoji","pai"),("eomeoni","mae"),("hyeongje","irmao"),("jae","irma"),
    ("haengbok","feliz"),("seulpeum","triste"),("apeuda","doente"),("pigonhada","cansado"),
    ("areumdaun","bonito"),("kkeun","feio"),("keuda","grande"),("jakda","pequeno"),
    ("ppareuda","rapido"),("nurida","devagar"),("deopda","quente"),("chupda","frio"),
    ("saeroun","novo"),("nalkeun","velho"),("jota","bom"),("nappuda","ruim"),
    ("sarang","amor"),("pyeonghwa","paz"),("jeonjaeng","guerra"),("saengmyeong","vida"),
    ("jugeum","morte"),("huimang","esperanca"),("mid-eum","fe"),("sigan","tempo"),
    ("nal","dia"),("bam","noite"),("hae","ano"),("eoje","ontem"),
    ("naeil","amanha"),("eonjena","sempre"),("gyeolko","nunca"),("jigeum","agora"),
    ("yeogi","aqui"),("jeogi","ali"),("annyeong","ola"),("annyeong","tchau"),
    ("gomabseubnida","obrigado"),("joesonghabnida","desculpe"),("ppalgan","vermelho"),("paran","azul"),
    ("choyeok","verde"),("noran","amarelo"),("hayan","branco"),("geom-eun","preto"),
    ("bap","arroz"),("gogi","carne"),("yacha","salada"),("kimchi","conserva"),
    ("meori","cabeca"),("nun","olho"),("gwi","orelha"),("ko","nariz"),
    ("ip","boca"),("son","mao"),("bal","pe"),("palam","braco"),
    ("dari","perna"),("simjang","coracao"),("meoritkarak","cabelo"),("i","dente"),
    ("hannyeo","lingua"),("eodeum","escuro"),("bit","luz"),("nalssi","clima"),
    ("yeol","quente"),("chagaun","frio"),("dadeut","quente"),("sseul","usar"),
    ("mekda","comer"),("masida","beber"),("boda","ver"),("deutda","ouvir"),
    ("ilda","ler"),("sseuda","escrever"),("malhada","falar"),("baeuda","aprender"),
    ("garicheuda","ensinar"),("nolda","brincar"),("ilhada","trabalhar"),("sada","comprar"),
    ("palda","vender"),("yori","cozinhar"),("jjitda","lavar"),("kkkeuthada","limpar"),
    ("guda","andar"),("ttwida","correr"),("anjda","sentar"),("seoda","ficar em pe"),
    ("nupda","deitar"),("kkaeda","acordar"),("jada","dormir"),("kkumkkuda","sonhar"),
    ("utda","rir"),("ulda","chorar"),("oeda","gritar"),("sokda","falar baixo"),
    ("saenggaghada","pensar"),("alda","saber"),("midda","acreditar"),("ihaehada","entender"),
    ("giokhada","lembrar"),("ijeuda","esquecer"),("wonhada","querer"),("pilyohada","precisar"),
    ("tto","tambem"),("aju","muito"),("deo","mais"),("deol","menos"),
    ("chungbunhan","suficiente"),("ajik","ainda"),("imi","ja"),("geujeo","apenas"),
    ("man","somente"),("geoui","quase"),("kkaji","ate"),("dasie","novamente"),
    ("hamkke","juntos"),("honja","sozinho"),("yeoreum","verao"),("gyeoul","inverno"),
    ("bom","primavera"),("ga-eul","outono"),("wol-yoil","segunda"),("hwayoil","terca"),
    ("suyoil","quarta"),("mogyoil","quinta"),("geumyoil","sexta"),("toyoil","sabado"),
    ("iryoil","domingo"),("ir-wol","janeiro"),("i-wol","fevereiro"),("sam-wol","marco"),
    ("sa-wol","abril"),("o-wol","maio"),("yu-wol","junho"),("chil-wol","julho"),
    ("pal-wol","agosto"),("gu-wol","setembro"),("si-wol","outubro"),("sib-il-wol","novembro"),
    ("sib-i-wol","dezembro"),("il","um"),("i","dois"),("sam","tres"),
    ("sa","quatro"),("o","cinco"),("yuk","seis"),("chil","sete"),
    ("pal","oito"),("gu","nove"),("sip","dez"),("baek","cem"),
    ("cheon","mil"),("eokkae","ombro"),("heori","cintura"),("balmok","tornozelo"),
    ("sonmok","pulso"),("muleup","joelho"),("pal","braco"),("son","mao"),
    ("bal","pe"),("meori","cabeca"),("eolgul","rosto"),("nun","olho"),
    ("ko","nariz"),("ip","boca"),("gwi","orelha"),    ("sonkarak","dedo"),
    ("chaek","livro"),("pen","caneta"),("jong-i","papel"),("yeonpil","lapis"),
    ("sik","relogio"),("an-gyeong","oculos"),("udae","guarda-chuva"),
    ("gabang","mochila"),("jigap","carteira"),("yeolsoe","chave"),
    ("mun","porta"),("chang","janela"),("byeog","parede"),("jadongcha","carro"),
    ("ucheguk","correio"),("eunhaeng","banco"),("seogwon","livraria"),
    ("yaksok","promessa"),("insa","cumprimento"),("jinjja","verdadeiro"),
    ("geojit","mentira"),("jinsil","verdade"),("jayu","liberdade"),
    ("pyeongdeung","igualdade"),("gyub", "regra"),("jeongui","justica"),
    ("jeongmal","realmente"),("aju","muito"),("jogeum","um pouco"),
    ("dasi","novamente"),("nun","olho"),("ko","nariz"),("ip","boca"),
    ("gwi","orelha"),("son","mao"),("bal","pe"),("meori","cabeca"),
    ("eokkae","ombro"),("muleup","joelho"),("pal","braco"),
    ("saek","cor"),("ppalgan","vermelho"),("paran","azul"),("choyeok","verde"),
    ("noran","amarelo"),("hayan","branco"),("geom-eun","preto"),
    ("hoesaek","cinza"),("juhwang","laranja"),("bora","roxo"),
    ("dal","lua"),("byeol","estrela"),("haendeupon","telefone"),
    ("kkeut","fim"),("sijak","inicio"),("junggan","meio"),
    ("wi","cima"),("arae","baixo"),("ap","frente"),("dwi","tras"),
    ("oenjjok","esquerda"),("oreunjjok","direita"),
    ("an","dentro"),("bak","fora"),("op","acima"),("mit","abaixo"),
]

# ====================== FACTUAL DATA ======================

BIBLE_FACTS = [
    ("Quem construiu a Arca de Noe?",["Noe","Moises","Abraao","Davi"],0),
    ("Quantos livros tem a Biblia?",["66","27","39","73"],0),
    ("Quem foi o primeiro rei de Israel?",["Saul","Davi","Salomao","Josue"],0),
    ("Onde nasceu Jesus?",["Belem","Nazare","Jerusalem","Galileia"],0),
    ("Quantos dias Deus levou para criar o mundo?",["6","7","5","10"],0),
    ("Quem escreveu o livro de Salmos em sua maioria?",["Davi","Salomao","Moises","Josue"],0),
    ("Qual o menor livro da Biblia?",["2 Joao","Filemom","Judas","Obadias"],0),
    ("Quem foi engolido por um grande peixe?",["Jonas","Jose","Daniel","Elias"],0),
    ("Quantos apostolos Jesus escolheu?",["12","7","10","14"],0),
    ("Qual o primeiro mandamento?",["Amar a Deus sobre todas as coisas","Nao matar","Nao roubar","Honrar pai e mae"],0),
    ("Quem liderou o Exodo do Egito?",["Moises","Josue","Arao","Abraao"],0),
    ("Em que dia Jesus ressuscitou?",["Domingo","Sabado","Sexta","Quinta"],0),
    ("Qual o livro mais longo da Biblia?",["Salmos","Isaías","Jeremias","Genesis"],0),
    ("Quem traiu Jesus?",["Judas","Pedro","Tome","Joao"],0),
    ("O que Deus criou no primeiro dia?",["Luz","Ceu","Terra","Animais"],0),
    ("Quem escreveu o Apocalipse?",["Joao","Pedro","Paulo","Tiago"],0),
    ("Qual profeta foi levado ao ceu em carro de fogo?",["Elias","Eliseu","Isaías","Jeremias"],0),
    ("Quantos irmaos tinha Jose do Egito?",["11","7","10","12"],0),
    ("Onde os 10 mandamentos foram dados?",["Monte Sinai","Monte Siao","Monte das Oliveiras","Monte Carmelo"],0),
    ("Quem foi o homem mais velho na Biblia?",["Matusalem","Noe","Adao","Set"],0),
    ("Quantos evangelhos existem?",["4","3","5","6"],0),
    ("Qual o maior mandamento?",["Amar a Deus","Nao matar","Nao roubar","Honrar os pais"],0),
    ("Quem era o irmao de Moises?",["Arao","Josue","Calebe","Eleazar"],0),
    ("Quantos dias Jonas ficou dentro do peixe?",["3","7","40","2"],0),
    ("Quem foi o pai de Davi?",["Jesse","Saul","Samuel","Boaz"],0),
    ("Qual cidade foi destruida junto com Sodoma?",["Gomorra","Jerico","Babel","Nínive"],0),
    ("Quem interpretou o sonho do farao?",["Jose","Daniel","Moises","Samuel"],0),
    ("Quantos dias e noites choveu no diluvio?",["40","7","30","50"],0),
    ("Quem foi o sucessor de Moises?",["Josue","Calebe","Arao","Eleazar"],0),
    ("Qual o nome da mae de Jesus?",["Maria","Ana","Isabel","Marta"],0),
    ("Onde Jesus foi batizado?",["Rio Jordao","Mar da Galileia","Mar Morto","Rio Nilo"],0),
    ("Quem foi lancado na cova dos leoes?",["Daniel","Jose","Jeremias","Ezequiel"],0),
    ("Qual apostolo negou Jesus tres vezes?",["Pedro","Judas","Tome","Tiago"],0),
    ("Quantos livros tem o Novo Testamento?",["27","21","39","33"],0),
    ("Quantos livros tem o Velho Testamento?",["39","27","46","33"],0),
    ("Quem foi o profeta que casou com prostituta?",["Oseias","Isaías","Jeremias","Ezequiel"],0),
    ("Qual o nome do gigante morto por Davi?",["Golias","Sansao","Enaque","Ogue"],0),
    ("Quem foi o homem mais sabio da Biblia?",["Salomao","Davi","Moises","Daniel"],0),
    ("O que significa Emanuel?",["Deus conosco","Filho de Deus","Salvador","Messias"],0),
    ("Quantos anos viveu Moises?",["120","90","110","150"],0),
    ("Quem foi o primeiro homem criado?",["Adao","Eva","Caim","Abel"],0),
    ("Onde Jesus andou sobre as aguas?",["Mar da Galileia","Rio Jordao","Mar Morto","Mediterraneo"],0),
    ("Quem foi a primeira mulher?",["Eva","Maria","Sara","Rebeca"],0),
    ("Qual apostolo era cobrador de impostos?",["Mateus","Pedro","Joao","Tiago"],0),
    ("Quem foi o profeta do fogo no Monte Carmelo?",["Elias","Eliseu","Isaías","Jeremias"],0),
    ("Quantas pragas atingiram o Egito?",["10","7","12","5"],0),
    ("Qual o nome do irmao de Maria de Betania?",["Lazaro","Pedro","Joao","Tiago"],0),
    ("Quem escreveu o livro de Romanos?",["Paulo","Pedro","Tiago","Joao"],0),
    ("O que caiu de Jerico?",["As muralhas","O templo","O palacio","As portas"],0),
    ("Quem foi vendido como escravo no Egito?",["Jose","Moises","Daniel","Jeremias"],0),
    ("Qual apostolo foi martirizado com espada?",["Tiago","Pedro","Joao","Filipe"],0),
    ("Quantas estrelas Jose sonhou?",["11","7","12","10"],0),
    ("Qual o nome do anjo que anunciou o nascimento de Jesus?",["Gabriel","Miguel","Rafael","Lucas"],0),
    ("Quem foi o primo de Jesus?",["Joao Batista","Pedro","Tiago","Lucas"],0),
    ("Onde Paulo teve sua conversao?",["Damasco","Jerusalem","Roma","Antioquia"],0),
    ("Quem foi o pai de Salomao?",["Davi","Saul","Jesse","Boaz"],0),
    ("Qual apostolo era medico?",["Lucas","Mateus","Joao","Pedro"],0),
    ("Quanto tempo Israel andou no deserto?",["40 anos","7 anos","2 anos","30 anos"],0),
    ("O que Balaao tinha que falava?",["Jumenta","Cavalo","Camelo","Cordeiro"],0),
    ("Quem foi a mulher de Abraao?",["Sara","Rebeca","Raquel","Hagar"],0),
    ("Que fruto Adao e Eva comeram?",["Fruto proibido","Maca","Uva","Figo"],0),
    ("Quantos homens foram escritos como tendo ido ao ceu?",["2","3","1","4"],0),
    ("Quem foi o ultimo juiz de Israel?",["Samuel","Sansao","Gideao","Jefté"],0),
    ("Quem derrubou o templo de Dagom?",["Sansao","Gideao","Samuel","Davi"],0),
    ("Qual era a profissao de Paulo?",["Fabricante de tendas","Pescador","Medico","Carpinteiro"],0),
    ("O que significa Messias?",["Ungido","Rei","Salvador","Profeta"],0),
    ("Quem recebeu as tabuas da lei?",["Moises","Josue","Arao","Israel"],0),
    ("Quantos homens Sansao matou com queixada de jumento?",["1000","500","300","200"],0),
    ("Qual o ultimo livro da Biblia?",["Apocalipse","Genesis","Salmos","Mateus"],0),
    ("Quem foi o primeiro martir cristao?",["Estevao","Pedro","Tiago","Paulo"],0),
    ("O que Jesus disse na cruz: Esta ____?",["consumado","completo","terminado","acabado"],0),
    ("Quem ungiu Davi como rei?",["Samuel","Saul","Nata","Golias"],0),
    ("Quem foi o profeta que chorou muito?",["Jeremias","Isaías","Ezequiel","Oseias"],0),
    ("Onde a arca de Noe parou?",["Monte Ararate","Monte Sinai","Monte Carmelo","Monte Siao"],0),
    ("Quanto tempo Jesus jejuou no deserto?",["40 dias","30 dias","7 dias","50 dias"],0),
    ("Qual o nome do jardim onde Jesus orou?",["Getsemani","Eden","Oliveiras","Horto"],0),
    ("Quem enterrou Jesus?",["Jose de Arimateia","Pedro","Joao","Nicodemos"],0),
    ("Que rei comeu capim como boi?",["Nabucodonosor","Salomao","Davi","Acabe"],0),
    ("Quem fugiu de casa para um pais distante?",["Filho prodigo","Jose","Moises","Rute"],0),
    ("Qual mulher salvou Israel matando Sisara?",["Debora","Jael","Ester","Rute"],1),
    ("Quantos homens Jesus alimentou com 5 paes e 2 peixes?",["5000","4000","3000","7000"],0),
    ("Onde Davi matou Golias?",["Vale de Ela","Monte Gilboa","Rio Jordao","Betelem"],0),
    ("Qual apostolo escreveu mais livros no NT?",["Paulo","Pedro","Joao","Tiago"],0),
    ("O que Belsazar viu na parede?",["Mao escrevendo","Fogo","Anjo","Espada"],0),
    ("Quem foi a rainha que salvou os judeus?",["Ester","Vasti","Rute","Debora"],0),
    ("Qual cidade caiu com sete voltas de trombetas?",["Jerico","Ai","Babel","Hesbom"],0),
    ("Quantos anos Noe tinha quando veio o diluvio?",["600","500","700","800"],0),
    ("Quem viu a escada que ia ao ceu?",["Jacó","Abraao","Isaque","Jose"],0),
    ("Em que cidade Jesus nasceu?",["Belem","Nazare","Jerusalem","Cafarnaum"],0),
    ("Quem escreveu o livro de Atos?",["Lucas","Paulo","Pedro","Marcos"],0),
    ("Quantos anos Israel ficou no Egito?",["430","400","300","500"],0),
    ("Que profeta foi serrado ao meio?",["Isaías","Jeremias","Ezequiel","Daniel"],0),
    ("Quem foi o homem que nao morreu e foi levado?",["Enoque","Elias","Moises","Noe"],0),
    ("Quem foi Rute?",["Neta de Abraao","Mulher de Boaz","Mae de Davi","Irma de Noemi"],1),
    ("Qual cidade chamada cidade de Davi?",["Jerusalem","Betelem","Hebrom","Samaria"],1),
    ("Quantos dias Jesus ficou no tumulo?",["3","2","4","7"],0),
    ("Onde Jesus foi crucificado?",["Golgota","Monte Siao","Monte das Oliveiras","Monte Carmelo"],0),
    ("Qual profeta foi lancado numa cisterna?",["Jeremias","Isaías","Ezequiel","Daniel"],0),
    ("O que significa Aleluia?",["Louvai ao Senhor","Gloria a Deus","Amem","Bendito seja"],0),
    ("Quem foi o sumo sacerdote quando Jesus morreu?",["Caifás","Anas","Zacarias","Elias"],0),
    ("Quantos homens foram salvos na arca de Noe?",["8","7","6","10"],0),
    ("O que Elias fez descer do ceu?",["Fogo","Chuva","Anjos","Mana"],0),
    ("Qual apostolo era gemeo?",["Tome","Filipe","Bartolomeu","Andre"],0),
    ("O que significa a palavra Amem?",["Que assim seja","Obrigado","Louvado","Glorificado"],0),
    ("Quem foi o profeta que viu a roda dentro da roda?",["Ezequiel","Isaías","Jeremias","Daniel"],0),
    ("Qual o nome do mar que Jesus acalmou?",["Mar da Galileia","Mar Vermelho","Mar Morto","Mediterraneo"],0),
    ("Quanto tempo durou o reinado de Salomao?",["40 anos","20 anos","33 anos","50 anos"],0),
    ("O que Davi toca?",["Harpa","Lira","Flauta","Trombeta"],0),
    ("Quem foi a mulher de Lot que virou estatua de sal?",["Nome nao mencionado","Sara","Rebeca","Raquel"],0),
    ("Qual apostolo foi pescador antes de seguir Jesus?",["Pedro e Andre","Joao e Tiago","Mateus","Filipe"],0),
    ("O que caiu do ceu para alimentar Israel no deserto?",["Mana","Pao","Carne","Peixe"],0),
    ("Quantas pedras Davi pegou para enfrentar Golias?",["5","3","7","1"],0),
    ("Quem profetizou que Jesus nasceria de uma virgem?",["Isaías","Jeremias","Miqueias","Zacarias"],0),
    ("O que Paulo era antes de se converter?",["Fariseu","Saduceu","Escriba","Sacerdote"],0),
    ("Qual o primeiro milagre de Jesus?",["Agua em vinho","Multiplicacao","Cura","Ressurreicao"],0),
    ("O que significa a palavra Evangelho?",["Boas novas","Historia","Mensagem","Profecia"],0),
    ("Quantos homens escreveram a Biblia?",["Cerca de 40","12","27","66"],0),
    ("Qual o nome do servo de Abraao que buscou Rebeca?",["Eliézer","Ismael","Ló","Damasco"],0),
    ("Que animal Jesus montou ao entrar em Jerusalem?",["Jumento","Cavalo","Camelo","Mula"],0),
    ("O que Jesus fez no templo que irritou os fariseus?",["Expulsou vendedores","Pregou","Curou","Ornou"],0),
    ("Qual a ultima palavra de Jesus na cruz?",["Pai, em tuas maos entrego meu espirito","Esta consumado","Tenho sede","Deus meu, Deus meu"],0),
    ("O que Jesus respondeu sobre o maior mandamento?",["Amaras a Deus e ao proximo","Nao mataras","Guardaras o sabado","Nao roubaras"],0),
    ("O que e a parabola?",["Historia com ensinamento espiritual","Profecia","Milagre","Mandamento"],0),
    ("Quem era o imperador romano quando Jesus nasceu?",["Augusto","Tiberio","Nero","Caligula"],0),
    ("O que significa o nome Jesus?",["Salvador","Messias","Cristo","Filho de Deus"],0),
    ("O que e a santa ceia?",["Celebracao da ultima ceia de Jesus","Festa","Jejum","Culto"],0),
    ("Quem foi o anjo que apareceu a Maria?",["Gabriel","Miguel","Rafael","Uriel"],0),
    ("Quantas igrejas sao mencionadas no Apocalipse?",["7","12","3","5"],0),
    ("Quem acompanhou Paulo em suas viagens missionarias?",["Barnabe e Silas","Pedro","Tiago","Joao"],0),
    ("Qual o nome do fiscal que Jesus chamou para ser apostolo?",["Mateus","Zaqueu","Nicodemos","Bartolomeu"],0),
]

KNOWLEDGE_FACTS = [
    ("Qual a capital do Brasil?",["Brasilia","Rio de Janeiro","Sao Paulo","Salvador"],0),
    ("Em que ano o homem pisou na Lua pela primeira vez?",["1969","1965","1972","1967"],0),
    ("Qual o maior oceano do mundo?",["Pacifico","Atlantico","Indico","Artico"],0),
    ("Quantos paises na ONU?",["193","195","191","197"],0),
    ("Qual a maior montanha do mundo?",["Monte Everest","Kilimanjaro","Aconcagua","McKinley"],0),
    ("Onde foi a Copa 2022?",["Catar","Russia","Brasil","Alemanha"],0),
    ("Qual a moeda do Japao?",["Iene","Won","Yuan","Dolar"],0),
    ("Quem pintou a Mona Lisa?",["Leonardo da Vinci","Michelangelo","Rafael","Van Gogh"],0),
    ("Qual a lingua mais falada do mundo?",["Mandarim","Ingles","Espanhol","Hindi"],0),
    ("Quantos ossos tem o corpo humano?",["206","208","204","210"],0),
    ("Qual o pais mais populoso?",["India","China","EUA","Indonesia"],0),
    ("Quem escreveu Dom Quixote?",["Miguel de Cervantes","Machado de Assis","Fernando Pessoa","Jose Saramago"],0),
    ("Qual o menor pais do mundo?",["Vaticano","Monaco","San Marino","Liechtenstein"],0),
    ("Em que ano caiu o Muro de Berlim?",["1989","1987","1991","1985"],0),
    ("Quantos planetas no Sistema Solar?",["8","9","7","10"],0),
    ("Quem foi o primeiro presidente dos EUA?",["George Washington","Jefferson","Lincoln","Adams"],0),
    ("Qual a maior floresta do mundo?",["Amazonica","Congo","Taiga","Boreal"],0),
    ("Quando e o Dia da Independencia do Brasil?",["7 de setembro","15 de novembro","21 de abril","1 de maio"],0),
    ("Qual o elemento mais abundante no universo?",["Hidrogenio","Helio","Oxigenio","Carbono"],0),
    ("Qual o maior deserto do mundo?",["Antartida","Saara","Gobi","Kalahari"],0),
    ("Onde fica o Coliseu?",["Roma","Paris","Londres","Madri"],0),
    ("Quando terminou a Segunda Guerra?",["1945","1944","1946","1943"],0),
    ("Qual a capital da Franca?",["Paris","Londres","Madri","Berlim"],0),
    ("O que e a Camada de Ozono?",["Protetor solar da Terra","Tipo de gas","Nuvem","Tempestade"],0),
    ("O que e a globalizacao?",["Integracao economica mundial","Governo","Movimento","Revolucao"],0),
    ("O que e a ONU?",["Organizacao das Nacoes Unidas","Organizacao Militar","Banco","Acordo"],0),
    ("Qual a capital do Japao?",["Toquio","Quioto","Osaka","Nagoya"],0),
    ("Quem foi o primeiro homem no espaco?",["Yuri Gagarin","Neil Armstrong","Buzz Aldrin","John Glenn"],0),
    ("Qual o rio mais longo do mundo?",["Nilo","Amazonas","Yangtze","Mississippi"],1),
    ("Quantos continentes existem?",["6","5","7","4"],0),
    ("Qual o menor oceano?",["Artico","Pacifico","Atlantico","Indico"],0),
    ("Qual pais inventou o papel?",["China","Japao","Coreia","India"],0),
    ("O que e fotossintese?",["Processo das plantas","Filtracao","Respiração","Digestao"],0),
    ("Quando foi proclamada a Republica no Brasil?",["1889","1822","1888","1900"],0),
    ("Quem descobriu o Brasil?",["Pedro Alvares Cabral","Colombo","Vespucio","Gama"],0),
    ("Qual a capital da Argentina?",["Buenos Aires","Santiago","Lima","Bogota"],0),
    ("Em que ano foi a primeira Copa do Mundo?",["1930","1934","1950","1928"],0),
    ("Quem venceu a Copa de 2022?",["Argentina","Franca","Brasil","Alemanha"],0),
    ("Quem inventou a lampada?",["Thomas Edison","Einstein","Tesla","Newton"],0),
    ("O que mede a escala Richter?",["Terremotos","Furacões","Temperatura","Pressao"],0),
    ("Qual o maior animal do mundo?",["Baleia azul","Elefante","Girafa","Tubarao"],0),
    ("Quem foi Shakespeare?",["Escritor","Pintor","Rei","Cientista"],0),
    ("O que e energia solar?",["Energia do sol","Energia do vento","Energia da agua","Energia nuclear"],0),
    ("Quantos estados tem o Brasil?",["26","27","25","24"],0),
    ("Qual a capital da Australia?",["Canberra","Sydney","Melbourne","Perth"],0),
    ("O que e aquecimento global?",["Aumento da temperatura media","Poluicao","Desmatamento","Gas"],0),
    ("Quem foi Mahatma Gandhi?",["Lider pacifista","Rei","Cientista","Escritor"],0),
    ("O que e o PIB?",["Produto Interno Bruto","Banco","Indice","Taxa"],0),
    ("Qual o pais mais antigo do mundo?",["Japao","Egito","China","Grecia"],1),
    ("Onde fica a Muralha da China?",["China","Mongolia","India","Japao"],0),
    ("O que e a bolsa de valores?",["Mercado financeiro","Loja","Banco","Mercado"],0),
    ("Quem pintou o teto da Capela Sistina?",["Michelangelo","Da Vinci","Rafael","Donatello"],0),
    ("Qual o ponto mais alto do Brasil?",["Pico da Neblina","Pico da Bandeira","Monte Roraima","Pico da Agulha"],0),
    ("O que e democracia?",["Governo do povo","Ditadura","Monarquia","Anarquia"],0),
    ("Quantos fusos tem o Brasil?",["4","3","5","2"],1),
    ("O que e Inteligencia Artificial?",["Maquinas que simulam inteligencia","Robos","Computadores","Softwares"],0),
    ("Quem descobriu a penicilina?",["Alexander Fleming","Einstein","Pasteur","Newton"],0),
    ("Qual a religiao mais praticada?",["Cristianismo","Islamismo","Hinduísmo","Budismo"],0),
    ("O que e energia eolica?",["Energia do vento","Energia solar","Energia nuclear","Hidreletrica"],0),
    ("Quem foi Steve Jobs?",["Fundador da Apple","Cientista","Escritor","Politico"],0),
    ("O que e reciclagem?",["Reutilizacao de materiais","Lixo","Poluicao","Limpeza"],0),
    ("Qual o simbolo quimico da agua?",["H2O","CO2","NaCl","O2"],0),
    ("O que e tabela periodica?",["Elementos quimicos","Numeros","Cores","Fisica"],0),
    ("Qual o pais mais populoso da Africa?",["Nigeria","Etiopia","Egito","Africa do Sul"],0),
    ("O que e criptomoeda?",["Moeda digital","Moeda fisica","Açao","Titulo"],0),
    ("O que e biodiversidade?",["Variedade de seres vivos","Natureza","Animais","Plantas"],0),
    ("Quem foi a primeira mulher presidente do Brasil?",["Dilma Rousseff","Lula","Fernando Henrique","Bolsonaro"],0),
    ("O que e a Antarctica?",["Continente gelado","Oceano","Pais","Ilha"],0),
    ("Qual a capital do Canada?",["Ottawa","Toronto","Vancouver","Montreal"],0),
    ("O que e efeito estufa?",["Aquecimento natural da Terra","Poluicao","Gas","Clima"],0),
    ("O que e astronomia?",["Estudo dos astros","Estudo da terra","Ciencia","Fisica"],0),
    ("Quem foi Pitagoras?",["Matematico grego","Filosofo","Cientista","Escritor"],0),
    ("Qual a capital da Russia?",["Moscou","Sao Petersburgo","Kiev","Minsk"],0),
    ("Quem foi Platão?",["Filosofo grego","Cientista","Rei","Escritor"],0),
    ("O que sao biomas?",["Ecossistemas","Animais","Regioes","Climas"],0),
    ("Quantas horas tem um dia?",["24","12","48","36"],0),
    ("Quantos dias tem um ano bissexto?",["366","365","364","360"],0),
    ("Qual o simbolo do potassio?",["K","P","Pt","Po"],0),
    ("O que significa DNA?",["Acido desoxirribonucleico","Celula","Gene","Proteina"],0),
    ("Qual a capital da Suecia?",["Estocolmo","Oslo","Copenhague","Helsinque"],0),
    ("Qual e o pais mais extenso?",["Russia","Canada","China","EUA"],0),
    ("O que e fusao nuclear?",["Uniao de nucleos","Fissao","Energia","Fisica"],0),
    ("O que e LHC?",["Grande Colisor de Hadrons","Telescopio","Satelite","Computador"],0),
    ("Qual pais tem maior expectativa de vida?",["Japao","Suica","Australia","Espanha"],0),
    ("O que e quimica organica?",["Estudo do carbono","Quimica","Ciencia","Biologia"],0),
    ("O que e geologia?",["Estudo da terra","Ciencia","Fisica","Geografia"],0),
    ("O que e meteorologia?",["Estudo do clima","Ciencia","Fisica","Geografia"],0),
    ("O que e psicologia?",["Estudo da mente","Ciencia","Filosofia","Sociologia"],0),
    ("O que e economia?",["Ciencia dos recursos","Politica","Financas","Mercado"],0),
    ("O que e filosofia?",["Amor a sabedoria","Ciencia","Religiao","Politica"],0),
    ("O que e arqueologia?",["Estudo de artefatos antigos","Ciencia","Historia","Antropologia"],0),
    ("O que e linguistica?",["Estudo das linguas","Ciencia","Filosofia","Gramatica"],0),
    ("Qual a capital da Noruega?",["Oslo","Estocolmo","Copenhague","Helsinque"],0),
    ("Qual a capital da Finlandia?",["Helsinque","Oslo","Estocolmo","Copenhague"],0),
    ("Qual a capital da Dinamarca?",["Copenhague","Oslo","Estocolmo","Helsinque"],0),
    ("Quantos dentes tem um adulto?",["32","28","30","36"],0),
    ("Qual o maior osso do corpo humano?",["Femur","Tibia","Umero","Radio"],0),
    ("Qual o menor osso do corpo humano?",["Estribo","Martelo","Bigorna","Falange"],0),
    ("O que e a pressao arterial?",["Forca do sangue nas arterias","Batimento","Pulso","Respiraçao"],0),
    ("O que e diabetes?",["Doenca metabolica","Infeccao","Virus","Alergia"],0),
    ("O que e cancer?",["Crescimento celular anormal","Virus","Bacteria","Infeccao"],0),
    ("O que e HIV?",["Virus da imunodeficiencia humana","Bacteria","Fungo","Protozoario"],0),
    ("O que e vacina?",["Estimula imunidade","Medicamento","Antibiotico","Vitamina"],0),
    ("O que e hardware?",["Componentes fisicos","Programas","Dados","Sistema"],0),
    ("O que e software?",["Programas de computador","Componentes fisicos","Dados","Rede"],0),
    ("O que e a internet?",["Rede global de computadores","Programa","Site","Servidor"],0),
    ("Quem criou a World Wide Web?",["Tim Berners-Lee","Bill Gates","Steve Jobs","Larry Page"],0),
    ("O que significa www?",["World Wide Web","Web Wide World","World Web Wide","Wide World Web"],0),
    ("O que significa e-mail?",["Eletronic mail","Easy mail","Eletric mail","E-mail"],0),
    ("O que e um pixel?",["Menor ponto de uma imagem","Cor","Luz","Tela"],0),
    ("O que e Bluetooth?",["Comunicacao sem fio de curto alcance","Rede","Conexao","Fio"],0),
    ("O que e Wi-Fi?",["Rede sem fio","Internet","Conexao","Protocolo"],0),
    ("O que e 5G?",["Quinta geracao de rede movel","Internet","Wi-Fi","Bluetooth"],0),
    ("O que e uma base de dados?",["Colecao organizada de dados","Planilha","Arquivo","Programa"],0),
    ("O que e algoritmo?",["Sequencia de passos","Programa","Dados","Formula"],0),
]

IT_FACTS = [
    ("O que significa CPU?",["Central Processing Unit","Computer Personal Unit","Central Program Utility","Core Processing Unit"],0),
    ("Qual a funcao do sistema operacional?",["Gerenciar hardware e software","Navegar na internet","Editar imagens","Jogar"],0),
    ("O que e um IP?",["Identificador unico na rede","Internet Provider","Intellectual Property","Input Password"],0),
    ("Qual protocolo para paginas web?",["HTTP","FTP","SMTP","TCP"],0),
    ("O que significa RAM?",["Random Access Memory","Read Access Memory","Run Application Module","Real Audio Memory"],0),
    ("Qual a diferenca entre HDD e SSD?",["SSD e mais rapido","HDD e mais rapido","Sao iguais","SSD e mais barato"],0),
    ("O que e firewall?",["Sistema de seguranca de rede","Virus","Navegador","Linguagem"],0),
    ("O que significa DNS?",["Domain Name System","Data Network Service","Digital Standard","Direct Server"],0),
    ("Para que serve um roteador?",["Distribuir internet","Aumentar velocidade","Armazenar","Processar"],0),
    ("O que e cloud computing?",["Servicos sob demanda pela internet","Armazenamento local","Servidor fisico","Rede social"],0),
    ("Diferenca entre IPV4 e IPV6?",["IPV6 tem mais enderecos","IPV4 e mais seguro","IPV6 e mais lento","IPV4 nao existe"],0),
    ("O que e virtualizacao?",["Versoes virtuais de recursos fisicos","Realidade virtual","Jogos","Videos"],0),
    ("O que significa RAID?",["Redundant Array of Independent Disks","Random Access Drive","Remote Interface","Rapid Data"],0),
    ("Funcao de um switch de rede?",["Conectar dispositivos em rede local","Conectar internet","Armazenar","Processar"],0),
    ("O que e latencia?",["Atraso na transmissao","Velocidade","Largura de banda","Dados"],0),
    ("O que significa SaaS?",["Software as a Service","System as a Service","Server as a Service","Storage as a Service"],0),
    ("O que e ataque DDoS?",["Negacao de servico distribuido","Virus","Falha de hardware","Erro de software"],0),
    ("O que e container (Docker)?",["Ambiente isolado para aplicacoes","Hardware","Maquina virtual","Sistema"],0),
    ("O que significa IoT?",["Internet of Things","Input Output Terminal","Internal Tool","Integrated Technology"],0),
    ("O que e banco relacional?",["Dados em tabelas","Dados em arvore","Arquivos","Cache"],0),
    ("O que e a Lei de Moore?",["Capacidade dobra a cada 2 anos","Gravidade","Evolucao","Fisica"],0),
    ("O que e um bit?",["Menor unidade de informacao","Byte","Caractere","Numero"],0),
    ("Quantos bits tem um byte?",["8","16","4","32"],0),
    ("O que e Big Data?",["Grande volume de dados","Pequenos dados","Banco","Planilha"],0),
    ("O que e Machine Learning?",["Aprendizado de maquina","IA","Programacao","Robotica"],0),
    ("O que e um compilador?",["Traduz para linguagem de maquina","Navegador","Editor","Interpretador"],0),
    ("O que e um debugger?",["Ferramenta para encontrar erros","Navegador","Editor","Compilador"],0),
    ("O que e GitHub?",["Plataforma de hospedagem de codigo","Rede social","Site","Servidor"],0),
    ("O que e protocolo TCP/IP?",["Conjunto de protocolos","Navegador","Linguagem","Aplicativo"],0),
    ("O que e VPN?",["Rede Virtual Privada","Virus","Proxy","Servidor"],0),
    ("O que e criptografia?",["Codificacao de dados","Virus","Senha","Seguranca"],0),
    ("O que e phishing?",["Golpe online","Virus","Ataque","Fraude"],0),
    ("O que e malware?",["Software malicioso","Virus","Aplicativo","Jogo"],0),
    ("O que e backup?",["Copia de seguranca","Arquivo","Dados","Sistema"],0),
    ("O que e Active Directory?",["Diretorio da Microsoft","Banco","Rede","Servidor"],0),
    ("O que e DHCP?",["Configuracao automatica de IP","Roteador","Servidor","Rede"],0),
    ("O que e NAT?",["Traducao de enderecos de rede","Protocolo","Roteador","Firewall"],0),
    ("O que e VLAN?",["Rede Local Virtual","Roteador","Switch","Servidor"],0),
    ("O que e um datacenter?",["Infraestrutura de servidores","Predio","Empresa","Rede"],0),
    ("O que e DevOps?",["Integracao entre dev e ops","Linguagem","Ferramenta","Cargo"],0),
    ("O que e SLA?",["Acordo de nivel de servico","Lei","Contrato","Norma"],0),
    ("O que e ITIL?",["Boas praticas de TI","Lei","Framework","Norma"],0),
    ("O que e ISO 27001?",["Norma de seguranca da informacao","Lei","Certificado","Padrao"],0),
    ("O que e SOC?",["Centro de Operacoes de Seguranca","Rede","Servidor","Sistema"],0),
    ("O que e pentest?",["Teste de penetracao","Virus","Ataque","Golpe"],0),
    ("O que e DMZ?",["Zona desmilitarizada na rede","Firewall","Roteador","Servidor"],0),
    ("O que e load balancer?",["Balanceador de carga","Servidor","Roteador","Switch"],0),
    ("O que e CDN?",["Rede de distribuicao de conteudo","Servidor","Cache","DNS"],0),
    ("O que e UPS?",["Fonte de alimentacao ininterrupta","Bateria","Gerador","Energia"],0),
    ("O que e hypervisor?",["Software de virtualizacao","Sistema","Servidor","Rede"],0),
    ("O que e VMware?",["Plataforma de virtualizacao","Linguagem","Banco","Sistema"],0),
    ("O que e snapshot?",["Instantaneo do sistema","Foto","Backup","Arquivo"],0),
    ("O que e disaster recovery?",["Recuperacao de desastres","Backup","Restore","Seguranca"],0),
    ("O que e cloud hibrida?",["Nuvem publica + privada","Nuvem","Servidor","Rede"],0),
    ("O que e AWS?",["Amazon Web Services","Servidor","Rede","Banco"],0),
    ("O que e Azure?",["Nuvem da Microsoft","AWS","Google Cloud","Servidor"],0),
    ("O que e IaaS?",["Infraestrutura como servico","Plataforma","Software","Rede"],0),
    ("O que e PaaS?",["Plataforma como servico","Infraestrutura","Software","Banco"],0),
    ("O que e SDN?",["Rede definida por software","Rede","Servidor","Firewall"],0),
    ("O que e orquestracao?",["Gerenciamento automatizado","Rede","Servidor","Sistema"],0),
    ("O que e Terraform?",["Infraestrutura como codigo","Linguagem","Ferramenta","Banco"],0),
    ("O que e Ansible?",["Automacao de configuracao","Linguagem","Servidor","Rede"],0),
    ("O que e Prometheus?",["Sistema de monitoramento","Banco","Servidor","Rede"],0),
    ("O que e Grafana?",["Visualizacao de metricas","Banco","Servidor","Rede"],0),
    ("O que e ELK Stack?",["Elasticsearch, Logstash, Kibana","Linguagem","Banco","Servidor"],0),
    ("O que e a porta 80?",["HTTP","HTTPS","FTP","SSH"],0),
    ("O que e a porta 443?",["HTTPS","HTTP","FTP","SSH"],0),
    ("O que e a porta 22?",["SSH","HTTP","HTTPS","FTP"],0),
    ("O que e a porta 21?",["FTP","HTTP","HTTPS","SSH"],0),
    ("O que e a porta 3306?",["MySQL","PostgreSQL","MongoDB","Redis"],0),
    ("O que e a porta 5432?",["PostgreSQL","MySQL","MongoDB","Redis"],0),
    ("O que e a porta 27017?",["MongoDB","MySQL","PostgreSQL","Redis"],0),
    ("O que e a porta 6379?",["Redis","MongoDB","MySQL","PostgreSQL"],0),
    ("O que significa CLI?",["Command Line Interface","Computer Line","Central Logic","Code Link"],0),
    ("O que significa GUI?",["Graphical User Interface","General Utility","Great Interface","Group Unit"],0),
    ("O que significa API?",["Application Programming Interface","Application Process","Automatic Program","Advanced Protocol"],0),
    ("O que e JSON?",["JavaScript Object Notation","Java Source","Just System","Java Standard"],0),
    ("O que e XML?",["Extensible Markup Language","Extra Markup","Execute Markup","X Format"],0),
    ("O que significa YAML?",["YAML Ain't Markup Language","Yet Another Language","Your Markup","YAML"],0),
    ("O que e um servidor proxy?",["Intermediario entre cliente e servidor","Virus","Firewall","Roteador"],0),
    ("O que e uma VPS?",["Servidor Privado Virtual","Virus","Proxy","VPN"],0),
]

FULLSTACK_FACTS = [
    ("O que e HTML?",["Linguagem de marcacao","Linguagem de programacao","Banco","Servidor"],0),
    ("Diferenca entre let, var e const?",["Escopo e imutabilidade","Nao ha","Tipo de loop","Funcoes"],0),
    ("O que e API REST?",["Interface entre sistemas","Banco","Linguagem","Servidor"],0),
    ("Qual banco e NoSQL?",["MongoDB","MySQL","PostgreSQL","SQLite"],0),
    ("O que significa SQL?",["Structured Query Language","Simple Query","Standard Logic","Sequential Query"],0),
    ("O que e Node.js?",["Runtime JavaScript server","Framework front-end","Banco","Editor"],0),
    ("O que significa CSS?",["Cascading Style Sheets","Computer Style","Creative Sheets","Central Service"],0),
    ("Qual ORM do Python?",["SQLAlchemy","Prisma","Sequelize","TypeORM"],0),
    ("O que e Git?",["Controle de versao","Linguagem","Banco","Servidor"],0),
    ("Diferenca entre GET e POST?",["GET le, POST envia","GET e seguro","POST rapido","Nao ha"],0),
    ("O que significa JWT?",["JSON Web Token","Java Tool","JavaScript Type","JSON Test"],0),
    ("Qual comando inicia Git?",["git init","git start","git create","git new"],0),
    ("O que e TypeScript?",["Superset JavaScript com tipos","Framework","Banco","Linguagem"],0),
    ("O que faz Docker Compose?",["Gerencia containers","Cria imagens","Monitora","Faz deploy"],0),
    ("O que e CI/CD?",["Integracao/Entrega Continua","Codigo","Compilacao","Cache"],0),
    ("Metodo HTTP para atualizar?",["PUT","POST","GET","DELETE"],0),
    ("O que e Next.js?",["Framework React SSR/SSG","Servidor","Banco","Editor"],0),
    ("O que significa ORM?",["Object-Relational Mapping","Online Resource","Object Request","Output Return"],0),
    ("O que e hook no React?",["Funcao de estado","Evento","Ciclo de vida","Metodo"],0),
    ("O que sao microservicos?",["Servicos independentes","Monolito","Banco","Framework"],0),
    ("O que e GraphQL?",["Linguagem de consulta","Banco grafico","Framework","Servidor"],0),
    ("Qual cloud lider?",["AWS","Azure","Google Cloud","Oracle"],0),
    ("O que e Kubernetes?",["Orquestrador de containers","Servidor","Banco","Linguagem"],0),
    ("O que e React?",["Biblioteca JS para UI","Linguagem","Framework","Banco"],0),
    ("O que e Angular?",["Framework JS","Linguagem","Biblioteca","Servidor"],0),
    ("O que e Vue.js?",["Framework JS progressivo","Linguagem","Biblioteca","Banco"],0),
    ("O que e npm?",["Gerenciador de pacotes Node","Linguagem","Framework","Banco"],0),
    ("O que e Webpack?",["Empacotador de modulos","Servidor","Linguagem","Banco"],0),
    ("O que e Babel?",["Transpilador JavaScript","Compilador","Framework","Linguagem"],0),
    ("O que e DOM?",["Document Object Model","Linguagem","Framework","Banco"],0),
    ("O que e JSX?",["Sintaxe JSX","Linguagem","Framework","Banco"],0),
    ("O que e SPA?",["Single Page Application","Servidor","Banco","Rede"],0),
    ("O que e SSR?",["Server Side Rendering","Render","Cliente","Banco"],0),
    ("O que e Express.js?",["Framework Node.js server","Linguagem","Banco","Rede"],0),
    ("O que e Django?",["Framework Python web","Linguagem","Servidor","Banco"],0),
    ("O que e Flask?",["Microframework Python","Linguagem","Servidor","Banco"],0),
    ("O que e FastAPI?",["Framework Python APIs","Linguagem","Servidor","Banco"],0),
    ("O que e Spring Boot?",["Framework Java","Linguagem","Servidor","Banco"],0),
    ("O que e Laravel?",["Framework PHP","Linguagem","Servidor","Banco"],0),
    ("O que e Ruby on Rails?",["Framework Ruby","Linguagem","Servidor","Banco"],0),
    ("O que e ASP.NET?",["Framework Microsoft","Linguagem","Servidor","Banco"],0),
    ("O que e MySQL?",["Banco relacional","NoSQL","Cache","Servidor"],0),
    ("O que e PostgreSQL?",["Banco relacional avancado","NoSQL","Cache","MySQL"],0),
    ("O que e SQLite?",["Banco embutido","Servidor","MySQL","NoSQL"],0),
    ("O que e MongoDB?",["NoSQL documental","Relacional","Cache","Grafo"],0),
    ("O que e Redis?",["Banco em memoria","Relacional","NoSQL","Cache"],0),
    ("O que e Elasticsearch?",["Motor de busca","Banco","Cache","Servidor"],0),
    ("O que e index?",["Acelera consultas","Tabela","Chave","Dado"],0),
    ("O que e chave estrangeira?",["Referencia entre tabelas","Chave primaria","Index","Dado"],0),
    ("O que e normalizacao?",["Organizacao de dados","Compressao","Criptografia","Index"],0),
    ("O que e ACID?",["Atomicidade,Consistencia,Isolamento,Durabilidade","Banco","Protocolo","Rede"],0),
    ("O que e transacao?",["Unidade de trabalho","Query","Tabela","Index"],0),
    ("O que e migration?",["Controle de versao do banco","Dados","Tabela","Query"],0),
    ("O que e MVC?",["Model-View-Controller","Linguagem","Banco","Servidor"],0),
    ("O que e middleware?",["Intermediario req-resp","Banco","Servidor","Rota"],0),
    ("O que e autenticacao?",["Verificacao de identidade","Autorizacao","Login","Senha"],0),
    ("O que e autorizacao?",["Permissao de acesso","Login","Senha","Token"],0),
    ("O que e OAuth?",["Protocolo de autorizacao","Autenticacao","Login","Token"],0),
    ("O que e CORS?",["Cross-Origin Resource Sharing","Seguranca","Protocolo","Rede"],0),
    ("O que e HTTPS?",["HTTP seguro","Protocolo","Criptografia","Rede"],0),
    ("O que e SSL/TLS?",["Protocolo de seguranca","HTTP","FTP","TCP"],0),
    ("O que e XSS?",["Cross-Site Scripting","Ataque","Virus","Banco"],0),
    ("O que e SQL Injection?",["Ataque de injecao SQL","Query","Banco","Dado"],0),
    ("O que e CSRF?",["Cross-Site Request Forgery","Ataque","Virus","Rede"],0),
    ("O que e WebSocket?",["Comunicacao bidirecional tempo real","HTTP","TCP","Rede"],0),
    ("O que e AJAX?",["JS assincrono","Linguagem","Framework","Biblioteca"],0),
    ("O que e Promise?",["Operacao assincrona","Funcao","Callback","Evento"],0),
    ("O que e async/await?",["Sintaxe assincrona","Promise","Callback","Evento"],0),
    ("O que e Event Loop?",["Loop de eventos JS","Thread","Processo","Funcao"],0),
    ("O que e Closure?",["Funcao com escopo externo","Objeto","Array","Variavel"],0),
    ("O que e Hoisting?",["Elevacao de declaracoes","Escopo","Closure","Evento"],0),
    ("O que e clean code?",["Codigo limpo","Codigo","Linguagem","Framework"],0),
    ("O que e SOLID?",["Principios de POO","Codigo","Linguagem","Framework"],0),
    ("O que e Design Pattern?",["Padrao de projeto","Codigo","Linguagem","Arquitetura"],0),
    ("O que e Singleton?",["Instancia unica","Objeto","Classe","Metodo"],0),
    ("O que e Factory?",["Criacao de objetos","Singleton","Classe","Metodo"],0),
    ("O que e Observer?",["Padrao de notificacao","Singleton","Factory","Classe"],0),
    ("O que e Props no React?",["Propriedades do componente","Estado","Funcao","Evento"],0),
    ("O que e State no React?",["Estado do componente","Prop","Funcao","Evento"],0),
    ("O que e useEffect?",["Efeito colateral em React","Estado","Prop","Evento"],0),
    ("O que e useState?",["Hook de estado","Efeito","Prop","Evento"],0),
    ("O que e Redux?",["Gerenciamento de estado","Biblioteca","Framework","Linguagem"],0),
    ("O que e Context API?",["Contexto no React","Estado","Prop","Evento"],0),
    ("O que e React Router?",["Roteamento no React","Estado","Prop","Navegacao"],0),
    ("O que e Axios?",["Cliente HTTP","Banco","Servidor","Linguagem"],0),
    ("O que e Fetch API?",["API nativa de requisicoes","Axios","Banco","Servidor"],0),
    ("O que e um endpoint?",["Ponto de acesso da API","Servidor","Banco","Rota"],0),
    ("O que e um middleware?",["Intermediario","Rota","Servidor","Banco"],0),
    ("O que e Dockerfile?",["Define a imagem Docker","Container","Servidor","Rede"],0),
    ("O que e docker-compose.yml?",["Define servicos Docker","Dockerfile","Container","Rede"],0),
    ("O que e .env?",["Variaveis de ambiente","Config","Docker","Banco"],0),
    ("O que e ESLint?",["Linter JavaScript","Formatador","Teste","Build"],0),
    ("O que e Prettier?",["Formatador de codigo","Linter","Teste","Build"],0),
    ("O que e Jest?",["Framework de testes JS","Linter","Formatador","Build"],0),
    ("O que e Cypress?",["Testes E2E","Unitario","Integracao","API"],0),
    ("O que e Postman?",["Teste de API","Banco","Servidor","Rede"],0),
    ("O que e Swagger?",["Documentacao de API","Teste","Banco","Servidor"],0),
    ("O que e TLS?",["Transport Layer Security","Protocolo","HTTP","Rede"],0),
    ("O que significa CD?",["Continuous Deployment","Continuous Delivery","Codigo","Cache"],1),
    ("O que e serverless?",["Computacao sem servidor","Sem servidor","Cloud","Funcao"],0),
]

# ====================== GENERATE ALL QUESTIONS ======================

def gen_pad(qs, facts, extra_generators=None):
    result = list(qs)
    for q, o, a in facts:
        result.append(make_q(q, o, a))
    if extra_generators:
        for gen in extra_generators:
            result.extend(gen)
    random.shuffle(result)
    return result[:500]

# ====================== SUPPLEMENTARY DATA ======================

BIBLE_CONCEPTS = [
    ("Golias","Gigante morto por Davi"),("Mana","Pao do ceu"),("Arca de Noe","Grande barco do diluvio"),
    ("Serpente","Enganou Eva no Eden"),("Caim","Matou Abel"),("Torre de Babel","Torre da confusao"),
    ("Davi","Pastor que virou rei"),("Salomao","Rei sabio"),("Sansao","Homem de forca"),
    ("Rute","Livro da fidelidade"),("Ester","Rainha que salvou os judeus"),("Jo","Livro da paciencia"),
    ("Matusalem","Homem mais velho"),("Getsemani","Jardim da agonia"),("Golgota","Local da cruz"),
    ("Bethlem","Cidade do nascimento"),("Nazare","Cidade de Jesus"),("Galileia","Regiao de Jesus"),
    ("Monte Sinai","Onde veio a lei"),("Monte Carmelo","Onde Elias orou"),("Mar Vermelho","Aberto por Moises"),
    ("Jordao","Onde Jesus foi batizado"),("Jerusalem","Cidade santa"),("Jerico","Cidade das muralhas"),
    ("Pentateuco","Cinco primeiros livros"),("Salmos","Livro de canticos"),("Provrbios","Livro de sabedoria"),
    ("Eclesiastes","Tudo e vaidade"),("Apocalipse","Revelacao"),("Evangelho","Boas novas"),
    ("Parabola","Historia com ensino"),("Milagre","Ato sobrenatural"),("Discipulo","Seguidor"),
    ("Apostolo","Enviado"),("Fariseu","Grupo religioso"),("Saduceu","Grupo que nao cria em anjos"),
    ("Escriba","Copista da lei"),("Gentio","Nao judeu"),("Sinagoga","Local de culto judaico"),
    ("Templo","Casa de Deus"),("Altar","Local de sacrificio"),("Arca da Alianca","Simbolo da presenca de Deus"),
    ("Tabernaculo","Tenda do encontro"),("Profeta","Porta-voz de Deus"),("Sacerdote","Mediador"),
    ("Levitico","Livro das leis"),("Deuteronomio","Segunda lei"),("Gomorra","Cidade destruida"),
    ("Sara","Mae da fe"),("Rebeca","Mulher de Isaque"),("Raquel","Mulher de Jaco"),
    ("Lia","Primeira mulher de Jaco"),("Hagar","Serva de Sara"),("Zaqueu","Publicano que subiu na arvore"),
    ("Lazaro","Ressuscitado por Jesus"),("Maria Madalena","Testemunha da ressurreicao"),("Bartolomeu","Apostolo"),
    ("Tomé","Apostolo que duvidou"),("Mateus","Cobrador de impostos"),("Andre","Primeiro discipulo"),
    ("Filipe","Apostolo"),("Simao Zelote","Apostolo"),("Judas Iscariotes","Traiu Jesus"),
    ("Paulo","Apostolo dos gentios"),("Silas","Companheiro de Paulo"),("Timoteo","Discipulo de Paulo"),
    ("Tito","Discipulo de Paulo"),("Barnabe","Companheiro de Paulo"),("Marcos","Escreveu o evangelho"),
    ("Lucas","Medico e escritor"),("Estevao","Primeiro martir"),("Pedro","Negou Jesus 3 vezes"),
    ("Caifás","Sumo sacerdote"),("Pilatos","Governador romano"),("Herodes","Rei da Judeia"),
    ("Cesar","Imperador romano"),("Anas","Sumo sacerdote"),("Satanas","Adversario"),
    ("Balaao","Profeta com jumenta"),("Gideao","Juiz com pouco homens"),("Debora","Juiza profetisa"),
    ("Sansao","Juiz forca"),("Jefté","Juiz que fez voto"),("Samuel","Profeta e juiz"),
    ("Elias","Profeta do fogo"),("Eliseu","Sucessor de Elias"),("Isaías","Profeta messianico"),
    ("Jeremias","Profeta chorarao"),("Ezequiel","Profeta das visoes"),("Daniel","Profeta dos sonhos"),
    ("Oseias","Profeta do amor"),("Jonas","Engolido pelo peixe"),("Naum","Profeta contra Nínive"),
    ("Ageu","Profeta do templo"),("Zacarias","Profeta das visoes"),("Malaquias","Ultimo profeta do AT"),
] * 1

BIBLE_PAIRS_TEMPLATES = [
    lambda t: f"Quem foi {t}?",
    lambda t: f"O que significa {t}?",
    lambda t: f"O que e {t}?",
    lambda t: f"Sobre {t}:",
]

KNOWLEDGE_CONCEPTS = [
    ("Astronomia","Estudo dos astros"),("Biologia","Estudo da vida"),("Quimica","Estudo da materia"),
    ("Fisica","Estudo das leis da natureza"),("Geologia","Estudo da terra"),("Oceanografia","Estudo dos oceanos"),
    ("Meteorologia","Estudo do clima"),("Psicologia","Estudo da mente"),("Sociologia","Estudo da sociedade"),
    ("Economia","Ciencia dos recursos"),("Filosofia","Amor a sabedoria"),("Teologia","Estudo de Deus"),
    ("Arqueologia","Estudo de artefatos antigos"),("Antropologia","Estudo do ser humano"),
    ("Linguistica","Estudo das linguas"),("Politica","Arte de governar"),("Etica","Estudo da moral"),
    ("Logica","Estudo do raciocinio"),("Retorica","Arte de persuadir"),("Gramatica","Estudo da lingua"),
    ("Algebra","Ramo da matematica"),("Geometria","Formas e espacos"),("Calculo","Ramo da matematica"),
    ("Estatistica","Analise de dados"),("Probabilidade","Estudo do acaso"),
    ("Termodinamica","Estudo do calor"),("Eletromagnetismo","Estudo da eletricidade"),
    ("Mecanica","Estudo do movimento"),("Otica","Estudo da luz"),("Acustica","Estudo do som"),
    ("Hidrostatica","Estudo dos liquidos"),("Cinética","Estudo da velocidade"),
    ("Evolucao","Teoria de Darwin"),("Genetica","Estudo dos genes"),("Ecologia","Estudo dos ecossistemas"),
    ("Botanica","Estudo das plantas"),("Zoologia","Estudo dos animais"),("Microbiologia","Estudo dos microorganismos"),
    ("Anatomia","Estudo do corpo"),("Fisiologia","Funcoes do corpo"),("Patologia","Estudo das doencas"),
    ("Farmacologia","Estudo dos medicamentos"),("Imunologia","Estudo do sistema imunologico"),
    ("Nefrologia","Estudo dos rins"),("Cardiologia","Estudo do coracao"),
    ("Dermatologia","Estudo da pele"),("Oftalmologia","Estudo dos olhos"),
    ("Neurologia","Estudo do sistema nervoso"),("Ortopedia","Estudo dos ossos"),
    ("Pediatria","Medicina infantil"),("Geriatria","Medicina do idoso"),
    ("Psiquiatria","Medicina mental"),("Oncologia","Estudo do cancer"),
    ("Capitalismo","Sistema economico"),("Socialismo","Sistema politico"),
    ("Democracia","Governo do povo"),("Monarquia","Governo de um rei"),
    ("Ditadura","Governo absoluto"),("República","Forma de governo"),
    ("Oligarquia","Governo de poucos"),("Teocracia","Governo religioso"),
    ("Anarquia","Ausencia de governo"),("Federalismo","Divisao de poderes"),
    ("Presidencialismo","Sistema de governo"),("Parlamentarismo","Sistema politico"),
    ("Liberalismo","Doutrina politica"),("Conservadorismo","Doutrina politica"),
    ("Nazismo","Ideologia alema"),("Fascismo","Ideologia italiana"),
    ("Comunismo","Doutrina de Marx"),("Feudalismo","Sistema medieval"),
    ("Escravidao","Trabalho forcado"),("Colonialismo","Dominio de territorios"),
    ("Imperialismo","Expansao de poder"),("Globalizacao","Integracao mundial"),
    ("Revolucao Industrial","Mudanca economica"),("Renascimento","Movimento cultural"),
    ("Iluminismo","Movimento intelectual"),("Romantismo","Movimento artistico"),
    ("Modernismo","Movimento cultural"),("Barroco","Estilo artistico"),
    ("Classicismo","Estilo artistico"),("Realismo","Movimento literario"),
    ("Naturalismo","Movimento literario"),("Simbolismo","Movimento literario"),
    ("Parnasianismo","Movimento literario"),("Arcádia","Movimento literario"),
    ("Trovadorismo","Primeira era literaria"),("Humanismo","Movimento filosofico"),
    ("Cubismo","Arte geometrica"),("Surrealismo","Arte do inconsciente"),
    ("Expressionismo","Arte emocional"),("Impressionismo","Arte da luz"),
]

K_PAIRS_TEMPLATES = [
    lambda t: f"O que estuda a {t}?" if t.endswith("a") or t.endswith("ia") else f"O que e {t}?",
    lambda t: f"Defina {t}:",
    lambda t: f"O que significa {t}?",
]

IT_CONCEPTS = [
    ("Kernel","Nucleo do SO"),("Shell","Interface de comandos"),("Driver","Controlador de dispositivo"),
    ("Firmware","Software embarcado"),("BIOS","Sistema basico de entrada"),("UEFI","Substituto do BIOS"),
    ("Boot","Inicializacao"),("Multithreading","Multiplas threads"),("Pipeline","Canal de processamento"),
    ("Cache","Armazenamento temporario"),("Buffer","Area de armazenamento"),("Heap","Memoria dinamica"),
    ("Stack","Pilha de memoria"),("Queue","Fila de dados"),("Deadlock","Impassse no sistema"),
    ("Starving","Fome de recurso"),("Race Condition","Condicao de corrida"),
    ("Mutex","Exclusao mutua"),("Semaphore","Controle de acesso"),("Thread","Linha de execucao"),
    ("Processo","Programa em execucao"),("Swap","Troca de memoria"),("Paginação","Gerenciamento de memoria"),
    ("Segmentação","Divisao de memoria"),("Virtual Memory","Memoria virtual"),
    ("Overclock","Aumento de clock"),("Cisc","Processador complexo"),("Risc","Processador reduzido"),
    ("Pipeline","Processamento em etapas"),("ALU","Unidade logica aritmetica"),
    ("FPU","Unidade de ponto flutuante"),("GPU","Processador grafico"),
    ("TPU","Processador tensor"),("NPU","Processador neural"),
    ("Register","Registrador"),("Cache L1","Cache nivel 1"),("Cache L2","Cache nivel 2"),
    ("Cache L3","Cache nivel 3"),("Barramento","Via de comunicacao"),
    ("SATA","Interface de disco"),("NVMe","Interface rapida SSD"),("PCIe","Barramento de expansao"),
    ("USB","Barramento universal"),("HDMI","Interface de video"),("DisplayPort","Interface de video"),
    ("VGA","Video antigo"),("DVI","Video digital"),("Thunderbolt","Interface rapida"),
    ("Ethernet","Rede cabada"),("Fiber","Fibra otica"),("Coaxial","Cabo de rede"),
    ("RJ45","Conector de rede"),("MAC","Endereco fisico"),("MTU","Unidade maxima de transmissao"),
    ("Ping","Teste de conectividade"),("Traceroute","Rastreamento de rota"),
    ("Netstat","Estatisticas de rede"),("Ifconfig","Configuracao de interface"),
    ("IWConfig","Configuracao wifi"),("Nslookup","Consulta DNS"),
    ("Dig","Ferramenta DNS"),("Curl","Ferramenta HTTP"),("Wget","Download via terminal"),
    ("Top","Monitor de processos"),("Ps","Lista processos"),("Kill","Mata processo"),
    ("Chmod","Muda permissoes"),("Chown","Muda dono"),("Grep","Busca em texto"),
    ("Sed","Editor de fluxo"),("Awk","Processador de texto"),("Alias","Apelido de comando"),
    ("Cron","Agendador de tarefas"),("Atd","Agendador unico"),("Systemd","Init system"),
    ("Journalctl","Logs do sistema"),("Syslog","Log do sistema"),("Ulimit","Limite de usuario"),
    ("Umask","Mascara de permissao"),("Nice","Prioridade de processo"),("Renice","Altera prioridade"),
]

IT_PAIRS_TEMPLATES = [
    lambda t: f"O que e {t}?",
    lambda t: f"Para que serve {t}?",
    lambda t: f"Definicao de {t}:",
]

FS_CONCEPTS = [
    ("Redux","Estado global React"),("MobX","Estado reativo"),("Zustand","Estado simples"),
    ("Recoil","Estado atomico"),("Jotai","Estado atomico"),("Vite","Build rapido"),
    ("Parcel","Empacotador zero config"),("Rollup","Empacotador de modulos"),
    ("Snowpack","Build rapido"),("Turbopack","Build rust"),("Rome","Toolchain unificada"),
    ("Biome","Formatador+linter"),("Stylelint","Linter CSS"),("Commitlint","Linter commits"),
    ("Husky","Hooks git"),("Lint-staged","Lint em staged"),("Semver","Versionamento semantico"),
    ("Conventional Commits","Padrao de commits"),("Gitflow","Fluxo git"),
    ("Trunk-based","Fluxo tronco"),("Feature Flag","Flag de recurso"),
    ("A/B Testing","Teste comparativo"),("Canary","Deploy gradual"),("Blue-green","Deploy seguro"),
    ("Dark Launch","Lancamento oculto"),("Feature Toggle","Chave de recurso"),
    ("i18n","Internacionalizacao"),("l10n","Localizacao"),("g11n","Globalizacao"),
    ("a11y","Acessibilidade"),("WCAG","Diretrizes de acessibilidade"),
    ("ARIA","Roles acessiveis"),("Semantic HTML","HTML semantico"),
    ("Microdata","Dados estruturados"),("Open Graph","Meta para redes sociais"),
    ("SEO","Otimizacao para buscadores"),("SSR","Renderizacao no servidor"),
    ("SSG","Geracao de site estatico"),("ISR","Regeneracao incremental"),
    ("CSR","Renderizacao no cliente"),("Hydration","Hidratacao React"),
    ("Suspense","Loading React"),("Lazy Loading","Carregamento tardio"),
    ("Code Splitting","Divisao de codigo"),("Tree Shaking","Remocao de codigo morto"),
    ("Minificacao","Compressao de codigo"),("Bundling","Empacotamento"),
    ("Transpilacao","Conversao de codigo"),("Polyfill","Compatibilidade"),
    ("Progressive Web App","App web progressivo"),("Service Worker","Trabalhador de servico"),
    ("Web Worker","Thread em background"),("PWA","App como web"),
    ("Manifest","Arquivo de config PWA"),("Cache API","Cache programatico"),
    ("IndexedDB","Banco no navegador"),("LocalStorage","Armazenamento local"),
    ("SessionStorage","Armazenamento sessao"),("Cookies","Dados do navegador"),
    ("JWT","Token JSON"),("OAuth2","Autorizacao"),("OpenID","Autenticacao descentralizada"),
    ("SAML","Autenticacao corporativa"),("LDAP","Diretorio de usuarios"),
    ("SSO","Login unico"),("MFA","Autenticacao multipla"),
    ("CORS","Compartilhamento entre origens"),("CSRF","Falsificacao de requisicao"),
    ("XSS","Script entre sites"),("CSP","Politica de seguranca"),
    ("HSTS","Seguranca HTTPS"),("HTTPS","HTTP seguro"),("SSL","Camada de sockets segura"),
    ("TLS","Seguranca de transporte"),("CA","Autoridade certificadora"),
    ("PKI","Infraestrutura de chave publica"),("RSA","Criptografia assimetrica"),
    ("AES","Criptografia simetrica"),("SHA","Hash seguro"),("MD5","Hash (inseguro)"),
    ("bcrypt","Hash de senha"),("Argon2","Hash de senha moderno"),
    ("Rate Limiting","Limitacao de requests"),("Throttling","Controle de fluxo"),
    ("Circuit Breaker","Padrao de resiliencia"),("Retry","Tentativa novamente"),
    ("Timeout","Tempo limite"),("Health Check","Verificacao de saude"),
    ("Graceful Shutdown","Desligamento gracioso"),("Load Shedding","Descarte de carga"),
    ("Bulkhead","Isolamento de falhas"),("Idempotencia","Operacao segura"),
]

FS_PAIRS_TEMPLATES = [
    lambda t: f"O que e {t}?",
    lambda t: f"Para que serve {t}?",
    lambda t: f"Definicao de {t}:",
]

# ====================== GENERATE ALL QUESTIONS ======================

def gen_pad(qs, facts, extra_concepts, extra_templates):
    result = list(qs)
    for idx, (q, o, a) in enumerate(facts):
        diff = 0 if idx < len(facts) * 0.33 else (1 if idx < len(facts) * 0.66 else 2)
        result.append(make_q(q, o, a, diff))
    extra = []
    for _ in range(500):
        term, defn = random.choice(extra_concepts)
        opts = [defn] + random.sample([d for t, d in extra_concepts if d != defn], min(3, len(extra_concepts)-1))
        random.shuffle(opts)
        ca = opts.index(defn)
        tmpl = random.choice(extra_templates)
        extra.append(make_q(tmpl(term), opts, ca, 2))
    result.extend(extra)
    random.shuffle(result)
    return result[:500]

ENGLISH_QUESTIONS = gen_lang_questions(make_lang_pairs(), "ingles")
SPANISH_QUESTIONS = gen_lang_questions(SP_BASE, "espanhol")
FRENCH_QUESTIONS = gen_lang_questions(FR_BASE, "frances")
KOREAN_QUESTIONS = gen_lang_questions(KO_BASE, "coreano")

BIBLE_QUESTIONS = gen_pad([], BIBLE_FACTS, BIBLE_CONCEPTS, BIBLE_PAIRS_TEMPLATES)
KNOWLEDGE_QUESTIONS = gen_pad([], KNOWLEDGE_FACTS, KNOWLEDGE_CONCEPTS, K_PAIRS_TEMPLATES)
IT_QUESTIONS = gen_pad([], IT_FACTS, IT_CONCEPTS, IT_PAIRS_TEMPLATES)
FULLSTACK_QUESTIONS = gen_pad([], FULLSTACK_FACTS, FS_CONCEPTS, FS_PAIRS_TEMPLATES)


print(f"[questions_data] Ingles: {len(ENGLISH_QUESTIONS)}")
print(f"[questions_data] Espanhol: {len(SPANISH_QUESTIONS)}")
print(f"[questions_data] Frances: {len(FRENCH_QUESTIONS)}")
print(f"[questions_data] Coreano: {len(KOREAN_QUESTIONS)}")
print(f"[questions_data] Bíblicas: {len(BIBLE_QUESTIONS)}")
print(f"[questions_data] Conhecimentos: {len(KNOWLEDGE_QUESTIONS)}")
print(f"[questions_data] Informatica: {len(IT_QUESTIONS)}")
print(f"[questions_data] Fullstack: {len(FULLSTACK_QUESTIONS)}")

QUESTIONS = {
    "📖 Bíblicas": BIBLE_QUESTIONS,
    "🌍 Conhecimentos Gerais": KNOWLEDGE_QUESTIONS,
    "🇬🇧 Inglês (Aprenda)": ENGLISH_QUESTIONS,
    "🇪🇸 Espanhol (Aprenda)": SPANISH_QUESTIONS,
    "🇫🇷 Francês (Aprenda)": FRENCH_QUESTIONS,
    "🇰🇷 Coreano (Aprenda)": KOREAN_QUESTIONS,
    "💻 Informática": IT_QUESTIONS,
    "🚀 Programação Fullstack": FULLSTACK_QUESTIONS,
}

CATEGORY_KEYS = list(QUESTIONS.keys())
